name: Publish to WinGet

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to publish (example: v0.1.1-alpha)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish release to WinGet
        uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: git-fire.git-fire
          installers-regex: '_windows_(386|amd64|arm64)\.zip$'
          release-tag: ${{ inputs.release_tag }}
          fork-user: git-fire
          token: ${{ secrets.WINGET_TOKEN }}
